
const Menu=[{
    id:1,
    Image:"src\NewComponent\Basic\Images\image3.jpg",
    name:"maggi",
    category:"Breakfast",
    price: 55,
    Description:"The son of an Italian-born mill owner, Julius Maggi's company was based in the Swiss village of Kemptthal, near Zurich, and produced wheat flours.",
},
{
    id:2,
    Image:"..\Images\image3.jpg",
    name:"Burger",
    category:"Lunch",
    price: 55,
    Description:"meat or vegetables cut into very small pieces and made into a flat round-shaped cutlet, that you eat between two pieces of bread",
},
{
    id:3,
    Image:"..\Images\image3.jpg",
    name:"noodles",
    category:"Dinner",
    price: 55,
    Description:"Noodles are typically made from unleavened wheat dough and are stretched, extruded, or rolled, and then cut into varying shapes. Noodles account for approximately 20%–50% of the total wheat consumed in Asia, and its popularity has extended",
},
{
    id:4,
    Image:"..\Images\image3.jpg",
    name:"samosa",
    category:"Dinner",
    price: 55,
    Description:"(locally known as maida) and stuffed with a filling, often a mixture of diced and cooked or mashed boiled potato, onions, green peas, lentils, ginger, spices and green chili. A samosa can be vegetarian or non-vegetarian, depending on the filling",
},
{
    id:5,
    Image:"..\Images\image3.jpg",
    name:"momo",
    category:"Breakfast",
    price: 55,
    Description:"Noodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and a",
},
{
    id:6,
    Image:"..\Images\image3.jpg",
    name:"breadsandwich",
    category:"Lunch",
    price: 55,
    Description:"Noodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and ag",
},
{
    id:7,
    Image:"..\Images\image3.jpg",
    name:"upma",
    category:"Lunch",
    price: 55,
    Description:"Noodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and a",
},
{
    id:8,
    Image:"..\Images\image3.jpg",
    name:"paties",
    category:"Lunch",
    price: 55,
    Description:"Noodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and aNoodles are typically made from unleavened wheat dough and a",
},
{
    id:9,
    Image:"..\Images\image3.jpg",
    name:"Rolls",
    category:"Lunch",
    price: 55,
    Description:"Noodles are typically made from unleavened wheat dough and a",
},

];
export default Menu;